apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-action-figure-hpa
  namespace: ai-action-figure
spec:
  minReplicas: 1
  maxReplicas: 10

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-action-figure

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
