name: Prod - Action Figure Generator
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ghcr-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env.production file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env.production

      - name: Build image and push to GHCR
        run: |
          docker pull ghcr.io/antonengelhardt/ai-action-figure:latest || true # Pull the image to cache
          docker build -t ghcr.io/antonengelhardt/ai-action-figure:latest -f Dockerfile .
          docker push ghcr.io/antonengelhardt/ai-action-figure:latest

  deploy:
    needs: ghcr-image
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ss-k8s-02

      - name: Deploy to Kubernetes
        run: kubectl rollout restart deployment ai-action-figure -n ai-action-figure

