name: Prod - Action Figure Generator
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ghcr-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env.production file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env.production

      - name: Build image and push to GHCR
        run: |
          docker pull ghcr.io/antonengelhardt/ai-action-figure:latest || true # Pull the image to cache
          docker build -t ghcr.io/antonengelhardt/ai-action-figure:latest -f Dockerfile .
          docker push ghcr.io/antonengelhardt/ai-action-figure:latest

  deploy:
    needs: ghcr-image
    environment: demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment ai-action-figure -n ai-action-figure
