name: Check Docker Build
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Try to build Docker Image
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GHCR
        run: |
          docker pull ghcr.io/savestrike/ai-action-figure:pr-${{ github.event.number }} || true # Pull the image to cache
          docker build -t ghcr.io/savestrike/ai-action-figure:pr-${{ github.event.number }} -f Dockerfile.dev .
          docker push ghcr.io/savestrike/ai-action-figure:pr-${{ github.event.number }}
